FROM gcr.io/google_containers/etcd-amd64:3.0.17
FROM gcr.io/google_containers/kube-apiserver-amd64:v1.7.4
FROM gcr.io/google_containers/kube-controller-manager-amd64:v1.7.4
FROM gcr.io/google_containers/kube-scheduler-amd64:v1.7.4
FROM gcr.io/google_containers/kube-proxy-amd64:v1.7.4
FROM gcr.io/google_containers/pause-amd64:3.0
FROM gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4
FROM gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4
FROM gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4
