FROM quay.io/calico/kube-policy-controller:v0.7.0             
FROM kubernetesdashboarddev/kubernetes-dashboard-amd64:head             
FROM quay.io/calico/node:v2.4.1          
FROM gcr.io/google_containers/kube-controller-manager-amd64:v1.7.3            
FROM gcr.io/google_containers/kube-apiserver-amd64:v1.7.3           
FROM gcr.io/google_containers/kube-scheduler-amd64:v1.7.3           
FROM gcr.io/google_containers/kube-proxy-amd64:v1.7.3             
FROM quay.io/calico/cni:v1.10.0          
FROM gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3           
FROM quay.io/coreos/etcd:v3.1.10           
FROM gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4             
FROM gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4           
FROM gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4           
FROM gcr.io/google_containers/etcd-amd64:3.0.17           
FROM gcr.io/google_containers/pause-amd64:3.0
